---
title: "Best models ME"
format: html
editor: source
---

## AIC

```{r combine individual fits, include=FALSE}
individual <- bind_rows(
  individual_fits_1_1 |> mutate(model = "linear mu, constant sigma"),
  individual_fits_1_2 |> mutate(model = "linear mu, poisson sigma"),
  individual_fits_1_3 |> mutate(model = "linear mu, modulated poisson sigma"),
  individual_fits_1_4 |> mutate(model = "linear mu, multiplicative sigma"),
  individual_fits_1_5 |> mutate(model = "linear mu, power sigma"),
  individual_fits_2_1 |> mutate(model = "power mu, constant sigma"),
  individual_fits_2_2 |> mutate(model = "power mu, poisson sigma"),
  individual_fits_2_3 |> mutate(model = "power mu, modulated poisson sigma"),
  individual_fits_2_4 |> mutate(model = "power mu, multiplicative sigma"),
  individual_fits_2_5 |> mutate(model = "power mu, power sigma"),
  individual_fits_3_1 |> mutate(model = "sym naka rushton mu, constant sigma"),
  individual_fits_3_2 |> mutate(model = "sym naka rushton mu, poisson sigma"),
  individual_fits_3_3 |> mutate(model = "sym naka rushton mu, modulated poisson sigma"),
  individual_fits_3_4 |> mutate(model = "sym naka rushton mu, multiplicative sigma"),
  individual_fits_3_5 |> mutate(model = "sym naka rushton mu, power sigma"),
  individual_fits_4_1 |> mutate(model = "asym naka rushton mu, constant sigma"),
  individual_fits_4_2 |> mutate(model = "asym naka rushton mu, poisson sigma"),
  individual_fits_4_3 |> mutate(model = "asym naka rushton mu, modulated poisson sigma"),
  individual_fits_4_4 |> mutate(model = "asym naka rushton mu, multiplicative sigma"),
  individual_fits_4_5 |> mutate(model = "asym naka rushton mu, power sigma"))
  
individual_fits <- individual |> 
  mutate(n_par = map_int(par, nrow)) |> 
  select(participant, model, log_lik, AIC, BIC, n_par)
```


```{r plot individual fits AIC, echo=FALSE}
ggplotly(ggplot() +
  facet_wrap(vars(participant), scales = "free") +
  geom_point(data = individual_fits,
             aes(x = "AIC", y = AIC, color = model))) 
  
```

Best model by participant

```{r}
individual_fits |> group_by(participant) |> slice_min(AIC)
```




```{r}


equation_model <- c(
  "asym naka rushton mu, power sigma" = "$\\mu = \\frac{kx^\\beta}{\\nu^{\\beta-\\alpha} + x^{\\beta-\\alpha}}, \\sigma = \\sigma_0 + q\\mu^\\gamma$",
  "asym naka rushton mu, modulated poisson sigma q" = "$\\mu = \\frac{kx^\\beta}{\\nu^{\\beta-\\alpha} + x^{\\beta-\\alpha}}, \\sigma = \\sigma_0 + q\\sqrt{\\mu + g^2\\mu}$",
  "asym naka rushton mu, poisson sigma q" = "$\\mu = \\frac{kx^\\beta}{\\nu^{\\beta-\\alpha} + x^{\\beta-\\alpha}}, \\sigma = \\sigma_0 + q\\mu^{0.5}$",
  "sym naka rushton mu, power sigma" = "$\\mu = \\frac{kx^\\beta}{\\nu^\\beta + x^\\beta}, \\sigma = \\sigma_0 + q\\mu^\\gamma$",
  "asym naka rushton mu, multiplicative sigma" = "$\\mu = \\frac{kx^\\beta}{\\nu^{\\beta-\\alpha} + x^{\\beta-\\alpha}}, \\sigma = \\sigma_0 + q\\mu$"
)

best_ind_model <- individual_fits |> 
  group_by(participant) |> 
  slice_min(AIC, n = 1, with_ties = FALSE) |> 
  ungroup() |> 
  count(model, name = "n_win") 

weight_p <- individual_fits |> 
  group_by(participant) |> 
  mutate(min_AIC = min(AIC),
         delta_ind = AIC - min_AIC,
         weight_ind = exp(-0.5 * delta_ind) / sum(exp(-0.5 * delta_ind))) |> 
  group_by(model) |>
  summarise(weight_mean = mean(weight_ind)) |> 
  arrange(desc(weight_mean))

t_AIC_values <- individual_fits |> 
  group_by(model) |> 
  summarise(n_par = unique(n_par),
            Sum_AIC = sum(AIC)) |> 
  mutate(delta_AIC = Sum_AIC - min(Sum_AIC)) |> 
  left_join(weight_p, by = "model") |> 
  inner_join(best_ind_model, by = "model") |> 
  select(model, n_win, Sum_AIC, delta_AIC, weight_mean) |>
  arrange(Sum_AIC) |> 
  mutate(model = case_when(
    model %in% names(equation_model) ~ equation_model[model],
    TRUE ~ model))


t_s1 <- t_AIC_values |> 
  gt() |> 
  fmt_markdown(columns = model) |>
  cols_label(
    model = "Model",
    n_win = "N",
    Sum_AIC = "AIC",
    delta_AIC = "ΔAIC",
    weight_mean = "wAIC"
  ) |>
  fmt_number(columns = c(Sum_AIC, delta_AIC), decimals = 0, use_seps = FALSE) |>
  fmt_number(columns = weight_mean, decimals = 3) |>
  cols_align(align = "left", columns = model) |> 
  cols_align(align = "center", columns = c(n_win, Sum_AIC, delta_AIC, weight_mean)) |> 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels()
  ) |> 
  tab_options(
    table.font.names = "Times New Roman",
    table.border.top.color = "black",
    table.border.top.width = px(1.5),
    column_labels.border.bottom.color = "black",
    column_labels.border.bottom.width = px(1),
    table.border.bottom.color = "black",
    table.border.bottom.width = px(1.5),
    table_body.hlines.style = "none",
    table_body.vlines.style = "none",
    column_labels.vlines.style = "none",
    table.border.left.style = "none",
    table.border.right.style = "none",
    data_row.padding = px(8))
t_s1

#gtsave(data = t_s1, filename = "figures/t_s1.pdf")
  
```











