---
title: "Untitled"
editor: source
---

```{r}
individual_preds_4_5_a <- individual_preds_4_5 |>
  mutate(
  contrast=x*100)
  

m_dat_a <- m_dat |> 
  mutate(
  contrast=c*100)

m_summ_bin_a <- m_summ_bin |> 
  mutate(
  contrast=c*100)


m_delta_a <- m_delta |> 
  mutate(
  contrast=x*100)

d_prop_a <- d_prop |> 
  mutate(
  contrast_p = x_p*100,
  contrast_c = x_c*100)

d_psy_asym_noise_a <- d_psy |> 
  mutate(
  contrast_p = x_p*100,
  contrast_c = x_c*100)

d_delta_a <- d_delta |> 
  mutate(
  contrast=x*100)


```


```{r}
p_raw_data <- ggplot() + 
  facet_wrap(vars(participant), scales="free_y", axes= "all", axis.labels="margins") +
    geom_point(data = m_dat_a, aes(x = contrast, y = r_norm), size = .25, alpha=0.5, color="grey60", shape=16)+
    geom_line(data = individual_preds_4_5_a, 
              aes(x = contrast, y = mu), color = "#AA7575", linewidth=0.3)+
  geom_text(data = m_dat_a |> group_by(participant) |> slice(1),
              aes(x = -Inf, y = Inf,
                  label = participant),
              size = 2, hjust=-.5, vjust=1) +
  theme_paper(7) +
  scale_y_continuous(
  breaks = scales::pretty_breaks(n = 3), expand=expansion(mult = c(0, 0.1))) +
  scale_x_continuous(limits=c(NA,15), expand=c(0,0)) +
  theme(
    strip.text = element_blank(),
    strip.background = element_blank()) +
  xlab("Contrast (%)") +
  ylab("Normalized responses")
p_raw_data
```

```{r}
param_me_mu <- param_me |> 
  mutate(x = 0.7,
         y = 4.2)
step_mu <- 1.5

p_mean_mu <- ggplot() + 
  facet_wrap(vars(participant), axes= "all", axis.labels="margins") +
  geom_point(data = m_summ_bin_a, 
             aes(x = contrast, y = m_norm), size=0.75, color = "#AA7575", alpha=0.7, shape=16) +
  geom_line(data = individual_preds_4_5_a, 
              aes(x = contrast, y = mu), color = "#AA7575", linewidth=0.3) +
  geom_text(data = param_me_mu,aes(x = x, y = y,
                                        label = paste("beta ==", signif(p2, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 0.2) +
  geom_text(data = param_me_mu,aes(x = x, y = y, 
                                        label = paste("alpha ==", signif(-p4, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 1*step_mu) +
  geom_text(data = param_me_mu,aes(x = x, y = y, 
                                        label = paste("k ==", signif(p1, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 2*step_mu) +
  geom_text(data = param_me_mu,aes(x = x, y = y, 
                                        label = paste("nu ==", signif(p3*100, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 3*step_mu) +
  theme_paper(7) +
  theme(
    strip.text = element_blank(),
    strip.background = element_blank()) +
  scale_y_continuous(breaks = c(0,2,4), limits = c(NA, 5), expand=c(0,0)) +
  scale_x_continuous(limits=c(NA,15), expand=c(0,0)) +
  xlab("Contrast (%)") +
  ylab(expression(mu))
p_mean_mu
```


```{r}
 param_me_sigma <- param_me |> 
  mutate(x = if_else(participant %in% c("p02", "p09"), 7, 0.7),
    y = if_else(participant %in% c("p02", "p09"), 0.8, 1.8))

step_sigma <- 1.5

p_sigma <- ggplot() + 
  facet_wrap(vars(participant), axes= "all", axis.labels="margins") +
    geom_point(data = m_summ_bin_a, 
               aes(x = contrast, y = sta_dev_norm), size = 0.7, color = "navajowhite3", alpha=0.75, shape=16) +
    geom_line(data = individual_preds_4_5_a,
              aes(x = contrast, y = sigma), color = "navajowhite3", linewidth=0.3) +
  geom_text(data = param_me_sigma,aes(x = x, y = y,
                                        label = paste("q ==", signif(p5, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 0) +
  geom_text(data = param_me_sigma,aes(x = x, y = y, 
                                        label = paste("gamma ==", signif(p7, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 1*step_sigma) +
  geom_text(data = param_me_sigma,aes(x = x, y = y, 
                                        label = paste("sigma[0] ==", signif(p6, 2))),
            parse = TRUE, size = 1.5, hjust = 0, vjust = 2*step_sigma) +
  theme_paper(7) +
  theme(
    strip.text = element_blank(),
    strip.background = element_blank()) +
  scale_y_continuous(n.breaks = 3, limits = c(0, 2), expand=c(0,0)) +
  scale_x_continuous(limits=c(0,15), expand=c(0,0)) +
  xlab("Contrast (%)") +
  ylab(expression(sigma))
p_sigma
```


```{r}
p_m_delta <- m_delta_a |> 
  ggplot(aes(contrast, delta_m)) +
  facet_wrap(vars(participant), axes= "all", axis.labels="margins") +
  geom_line(color = "aquamarine4", linewidth=0.3) +
  theme_paper(7) +
    theme(
    strip.text = element_blank(),
    strip.background = element_blank()) +
  scale_y_continuous(n.breaks = 3, expand=c(0,0), limits=c(0,NA)) +
  scale_x_continuous(limits=c(0,15), expand=c(0,0)) +
  xlab("Contrast (%)") +
  ylab(expression(D[ME]))

p_m_delta
```


```{r}
p_fit <- plot_grid(
  p_raw_data,
  p_mean_mu,
  p_sigma,
  p_m_delta,
  nrow = 2,
  align = 'vh',
  labels = c("A", "B", "C", "D"),
  label_size = 10)
p_fit
ggsave("figures/p_fit.pdf", p_fit, width = 6, height = 4.2)
```


```{r}
plot_p_correct <- ggplot() +
  facet_wrap(vars(participant), ncol = 4, axes= "all", axis.labels="margins") +
  geom_point(data = d_prop_noise_a,
             aes(x = contrast_c, y = prop, color = factor(x_p*100)), shape = 16,  size = 0.75) +
  geom_line(data = d_psy_asym_noise_a,
            aes(x = contrast_c, y = prop, color = factor(x_p*100)), linewidth=0.3) +
  geom_text(data = d_prop_noise_a|> group_by(participant) |> slice(1), 
            aes(x = 7, y = .5, label = participant),
            fill = NA, label.color = NA, size = 2, hjust=0) +
  scale_color_manual(values = c("#CBB2DD", "#9F73C2","#7436A6","#4B1A78")) +
  theme_paper(7) +
  scale_y_continuous(breaks = seq(0, 1, .25)) +
  theme(legend.position = "none",
        strip.text = element_blank(),
        strip.background = element_blank()) +
  xlab("Contrast (%)") +
   ylab("Proportion correct") +

  scale_x_log10(limits=c(NA,15), expand=c(0,0))


legend_discr <- get_legend(
  plot_p_correct + 
    theme(legend.position = "right") +
    labs(color = "Reference (%)") +
    guides(color = guide_legend(ncol = 2)))


plot_p_correct_legend <- ggdraw(plot_p_correct) + 
  draw_grob(legend_discr, x = 0.81, y = 0.1, width = 0.15, height = 0.3)
plot_p_correct_legend

```



```{r}
p_d_delta <- d_delta_a |> 
  ggplot(aes(contrast, delta_d)) +
  facet_wrap(vars(participant), axes= "all", axis.labels="margins") +
  geom_line(color = "darkorchid4", linewidth = 0.3) +
  theme_paper(7) +
  scale_y_continuous(breaks = c(0, 200, 400), expand=c(0,0)) +
  scale_x_continuous(limits=c(0,15), expand=c(0,0)) +
   theme(
    strip.text = element_blank(),
    strip.background = element_blank()) +
  xlab("Contrast %") +
  ylab("D")
p_d_delta
ggsave("figures/p_d_delta.pdf", p_d_delta , width = 2.5, height = 1.75)
```

```{r}
p_deltas <- ggplot() +
  geom_line(data = m_delta_a, aes(contrast, delta_m), color = "aquamarine4", linewidth=0.3) +
  geom_line(data = d_delta_a, aes(contrast, delta_d), color = "darkorchid4", linewidth=0.3) +
  facet_wrap(vars(participant), axes= "all", axis.labels="margins") +
  geom_text(data =  m_delta_a|> group_by(participant) |> slice(1), 
            aes(x = 10, y = 350, label = participant),
            fill = NA, label.color = NA, size = 2, hjust=0) +
  theme_paper(7) +
  theme(strip.text = element_blank(),
        strip.background = element_blank()) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 2), expand=c(0,0), limits=c(0, NA)) +
  scale_x_continuous(limits=c(0, NA), expand=c(0,0)) +
  xlab("Contrast (%)") +
  ylab("D")

p_deltas
```

```{r}
p_discr <- plot_grid(
  plot_p_correct_legend,
  p_deltas,
  align = 'vh',
  nrow = 1,
  labels = c("a", "b"),
  label_size = 10)
p_discr
ggsave("figures/p_discr.png", p_discr, width = 6.5, height = 2.5)
```










```{r}
p_deltas_all <- ggplot(sum_deltas |> mutate(contrast=x*100)) +
  geom_line(aes(contrast, estimate, color = model), linewidth=0.3) +
  geom_ribbon(aes(contrast, ymin = conf.low, ymax = conf.high, fill = model), alpha = 0.1) +
  scale_color_manual(name=NULL,
                     values = c("darkorchid4", "aquamarine4"),
                     labels = c("delta_m" = "ME", "delta_d" = "Discr"),
                     guide = "legend") +
  scale_fill_manual(name=NULL,
                    values = c("darkorchid4", "aquamarine4"),
                    labels = c("delta_m" = "ME", "delta_d" = "Discr"),
                    guide = "legend") +
  geom_segment(
  data = filter(xx, sig == "yes"),
  aes(x = x*100,xend = x*100,y = 270, yend = 280),
  color = "grey") +
  theme_paper(7) +
  
  theme(legend.position = "right")+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 3), expand=c(0,0)) +
  #labs(title = "") +y_breaks(n = 3), expand=c(0,0)) +
  scale_x_continuous(expand=c(0,0), limits=c(0, NA)) +
  xlab("Contrast (%)") +
  ylab("D") +
  coord_cartesian(ylim=c(0, NA))
  
p_deltas_all

ggsave("figures/p_deltas_all.png", p_deltas_all, width = 2, height = 2)

```


```{r}
position_stats <- stats_comparison_chat(c_combined, c_max_m, c_max_d, x_label="Position")

p_position_cor <- position_stats$plot_cor +
    scale_y_continuous(breaks = c(0, .02, 0.04),
                       labels = c("0", "0.02", "0.04"),
                     limits = c(0,0.045), expand = expansion(mult = c(0,0))) +
      scale_x_continuous(breaks = c(0, .02, 0.04),
                       labels = c("0", "0.02", "0.04"),
                     limits = c(0,0.045), expand = expansion(mult = c(0,0))) +
  ylab(bquote(Position[Discr])) +
  xlab(bquote(Position[ME]))

p_position_cor
p_position_stats <- position_stats$plot_tt + scale_y_continuous(breaks=c(0,0.02, 0.04), labels = c("0", "0.02", "0.04"), limits = c(0, 0.04), expand = expansion(mult = c(0, 0.1)))
p_position_stats

```

```{r}
amplitude_stats <- stats_comparison_chat(max_combined, max_m, max_d, x_label = "Amplitude")

p_amplitude_cor <- amplitude_stats$plot_cor +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 2),
                     limits = c(0,500), , expand = expansion(mult = c(0,0))) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 2),
                     limits = c(0,500), , expand = expansion(mult = c(0,0))) +
  ylab(bquote(Amplitude[Discr])) +
  xlab(bquote(Amplitude[ME]))

p_amplitude_cor
p_amplitude_stats <- amplitude_stats$plot_tt + scale_y_continuous(breaks = c(0, 200, 400), limits = c(0, 500), , expand = expansion(mult = c(0, 0)))
p_amplitude_stats
```

```{r}
der_wb_stats <- stats_comparison_chat(c_combined_der, der_m, der_d, x_label = expression(w))

p_der_cor <- der_wb_stats$plot_cor +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 2),
                     limits = c(-2,-0.2), expand = expansion(mult = c(0,0))) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 2),
                     limits = c(-2,-0.2), expand = expansion(mult = c(0,0))) +
    ylab(bquote(w["Discr"])) +
    xlab(bquote(w["ME"]))

p_der_cor
p_der_wb_stats <- der_wb_stats$plot_tt + scale_y_continuous(breaks = c(-1.5, -1, -0.5),expand = expansion(mult = c(0.05, 0.05))) 
  
p_der_wb_stats
```


```{r}
comparison_stats <- 
  plot_grid(
    p_position_stats,
    p_amplitude_stats,
    p_der_wb_stats,
    p_position_cor,
    p_amplitude_cor,
    p_der_cor,
    ncol=3,
    align = 'hv',
    axis = 'tblr'
)

comparison_stats

ggsave("figures/comparison_stats1.png", comparison_stats,
       width = 5, height = 3)
```



```{r}
plot_grid(plot_p_correct_legend, 
         p_position_stats, 
         ncol = 1, 
         align = "h", 
         axis = "left")
```


```{r}

aligned_ab <- align_plots(p_discr, comparison_stats, align = 'h', axis = 'l')

gg <- plot_grid(
  aligned_ab[[1]],
  aligned_ab[[2]],
  ncol = 1)
gg


```
####################


```{r}

p_ampl <- plot_grid(
  p_amplitude_stats,
  p_amplitude_cor,
  ncol = 1,
  rel_heights = c(0.465, 0.545), 
  labels = c("   C", "   F"),
  label_size = 8,
  align = 'v',
  axis = 'l'
)

p_pos <- plot_grid(
  p_position_stats,
  p_position_cor,
  ncol = 1,
  rel_heights = c(0.465, 0.545), 
  labels = c("   D", "   G"),
  label_size = 8,
  align = 'v',
  axis = 'l'
)
p_pos

p_der <- plot_grid(
  p_der_wb_stats,
  p_der_cor,
  ncol = 1,
  rel_heights = c(0.465, 0.545), 
  labels = c("   E", "   H"),
  label_size = 8,
  align = 'v',
  axis = 'l'
)

p_stats <- plot_grid(
  p_ampl,
  p_pos,
  p_der,
  ncol = 3,
  align = 'hv',
  axis = 'tblr'       
)
p_stats

p_stats_deltas_all <- plot_grid(
  p_stats, 
  p_deltas_all, 
  labels = c("", "   I"),
  label_size = 8,
  nrow = 1)

plot_p_correct_legend_deltas <- plot_grid(
  plot_p_correct_legend, 
   labels = c("A", "B"),
  label_size = 8,
  p_deltas)

p <- plot_grid(
  plot_p_correct_legend_deltas, 
  p_stats_deltas_all, 
  align = 'vh',
  axis = 'l',
  ncol = 1)
p_stats_deltas_all

legend_sens <- get_legend(
  p_deltas_all + 
    guides(fill="none") +
    theme(legend.position = "right",
          legend.text = element_text(size=6),
          legend.key.size = unit(1, "lines"),
          legend.key.width = unit(0.5, "lines"),
          legend.key.height = unit(0.7, "lines")))

p_stats_deltas_all_legend <- ggdraw(p) + 
  draw_grob(legend_sens, x = 0.935, y = 0.57, width = 0.05, height = 0.1)

ggsave("figures/p_stats_deltas_all_legend.pdf", p_stats_deltas_all_legend, width = 6.8, height = 4.8)
```



